name: Bug report
description: Report something that is not working as expected.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Before submitting a bug report, please check that the bug is not already reported in the [issues](https://github.com/TeamFluXis/fluXis/issues)
  - type: dropdown
    attributes:
      label: Type
      options:
        - Crash/Error/Exception
        - Behavior
        - Performance
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: The version you encountered the bug on. (At the bottom of the first page of the settings menu)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the bug
      description: What exactly is happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Video
      description: If applicable, add screenshots or a video to help explain your problem.
    validations:
      required: false
