on: [push, pull_request]
name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: build
        run: dotnet publish -c Release fluXis.Desktop --output ./bin

      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: fluXis-ci-build-linux
          path: |
            bin/*
            !bin/runtimes/osx*
            !bin/runtimes/win*

  build-windows:
    name: Build (Windows)
    runs-on: windows-2022
    timeout-minutes: 25
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: build
        run: dotnet publish -c Release fluXis.Desktop --output ./bin

      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: fluXis-ci-build-windows
          path: |
            bin/*
            !bin/runtimes/osx*
            !bin/runtimes/linux*